# Generated by Django 6.0.3 on 2026-06-21 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=100)),
                ('vendor_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reward_type', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='KOC',
            fields=[
                ('koc_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('social_account', models.CharField(max_length=100)),
                ('bank_number', models.CharField(max_length=50)),
                ('bank_account', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Koc',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('guest_id', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion_code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(default='pending', max_length=50)),
                ('payment_status', models.CharField(default='unpaid', max_length=50)),
                ('shipping_status', models.CharField(default='unshipped', max_length=50)),
                ('address_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(db_column='vendor_id', max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(default='koc', max_length=20)),
                ('wallet_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('tax_id', models.CharField(db_column='tax_id', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('submission_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tasks_id', models.CharField(blank=True, max_length=100, null=True)),
                ('influencer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='api.admins')),
            ],
            options={
                'db_table': 'Admin_Audit_Logs',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(db_column='application_id', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='api.campaigns')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Application',
            },
        ),
        migrations.CreateModel(
            name='KOCMissionNew',
            fields=[
                ('kocmission_id', models.AutoField(db_column='kocmisson_id', primary_key=True, serialize=False)),
                ('stage', models.CharField(db_column='stage', max_length=50)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='api.application')),
            ],
            options={
                'db_table': 'KOC_Misson',
            },
        ),
        migrations.CreateModel(
            name='CouponNew',
            fields=[
                ('coupon_id', models.AutoField(db_column='coupon_id', primary_key=True, serialize=False)),
                ('promotion_code', models.CharField(db_column='promotion_code', max_length=100, unique=True)),
                ('discount_value', models.IntegerField(db_column='discount_value')),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('usage_count', models.IntegerField(db_column='usage_count', default=0)),
                ('total_commission', models.IntegerField(db_column='total_commission', default=0)),
                ('kocmission', models.ForeignKey(db_column='kocmisson_id', on_delete=django.db.models.deletion.CASCADE, to='api.kocmissionnew')),
            ],
            options={
                'db_table': 'Coupon',
            },
        ),
        migrations.CreateModel(
            name='KocWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_available', models.IntegerField(default=0)),
                ('balance_frozen', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('koc', models.OneToOneField(db_column='koc_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='api.koc')),
            ],
            options={
                'db_table': 'Koc_Wallet',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'db_table': 'Guest',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply_status', models.IntegerField(default=0)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion_code', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('cart_id', models.ForeignKey(db_column='cart_id', on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.AutoField(db_column='submission_id', primary_key=True, serialize=False)),
                ('submission_type', models.CharField(db_column='submission_type', max_length=50)),
                ('content_url', models.CharField(blank=True, db_column='content_url', max_length=500, null=True)),
                ('text_content', models.TextField(blank=True, db_column='text_content', null=True)),
                ('status', models.CharField(db_column='status', max_length=50)),
                ('vendor_feedback', models.TextField(blank=True, db_column='vendor_feedback', null=True)),
                ('submitted_time', models.DateTimeField(blank=True, db_column='submitted_time', null=True)),
                ('reviewed_time', models.DateTimeField(blank=True, db_column='reviewed_time', null=True)),
                ('kocmission', models.ForeignKey(db_column='kocmisson_id', on_delete=django.db.models.deletion.CASCADE, to='api.kocmissionnew')),
            ],
            options={
                'db_table': 'Submissions',
            },
        ),
        migrations.CreateModel(
            name='TrackingLogs',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_code', models.CharField(blank=True, db_column='promotion_code', max_length=100, null=True)),
                ('click_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Tracking_Logs',
            },
        ),
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payout_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('influencer_id', models.ForeignKey(db_column='influencer_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Payouts',
            },
        ),
        migrations.AddField(
            model_name='koc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='koc_profile', to='api.user'),
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('earnings_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Earnings',
            },
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('influencer', models.ForeignKey(db_column='influencer_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Commissions',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='CampaignParticipants',
            fields=[
                ('participants_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_coupon_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='api.campaigns')),
                ('influencer', models.ForeignKey(db_column='influencer_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Campaign_Participants',
            },
        ),
        migrations.CreateModel(
            name='CampaignApplications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='api.campaigns')),
                ('influencer', models.ForeignKey(db_column='influencer_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Campaign_Applications',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('detail_address', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='ServiceTickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.admins')),
                ('order_id', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order')),
                ('consumer_id', models.ForeignKey(blank=True, db_column='consumer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_consumer', to='api.user')),
                ('influencer_id', models.ForeignKey(blank=True, db_column='influencer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_influencer', to='api.user')),
                ('vendor_id', models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vendor')),
            ],
            options={
                'db_table': 'Service_Tickets',
            },
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_available', models.IntegerField(default=0)),
                ('balance_frozen', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='api.vendor')),
            ],
            options={
                'db_table': 'Vendor_Wallet',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Wishlist',
            },
        ),
    ]
