# Generated by Django 6.0.3 on 2026-06-15 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('Campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=100)),
                ('Vendor_id', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Reward_type', models.CharField(max_length=100)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
                ('Status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'api_campaigns',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('User_id', models.CharField(db_index=True, max_length=100)),
                ('Guest_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Promotion_code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(default='pending', max_length=50)),
                ('payment_status', models.CharField(default='unpaid', max_length=50)),
                ('shipping_status', models.CharField(default='unshipped', max_length=50)),
                ('Address_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('Order_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Product_id', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('Unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply_status', models.IntegerField(default=0)),
                ('order', models.ForeignKey(db_column='Order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'db_table': 'api_order_item',
            },
        ),
    ]
