# Generated by Django 6.0.3 on 2026-06-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kocmissionnew',
            table='Koc_Mission',
        ),
    ]
