# Generated by Django 6.0.3 on 2026-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kocwallet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendorwallet',
            name='id',
        ),
        migrations.AddField(
            model_name='kocwallet',
            name='wallet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vendorwallet',
            name='wallet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
