# Generated by Django 6.0.3 on 2026-06-22 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_kocmissionnew_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='product_id',
        ),
        migrations.CreateModel(
            name='CampaignProduct',
            fields=[
                ('campaign_product_id', models.AutoField(db_column='campaign_product_id', primary_key=True, serialize=False)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_products', to='api.campaigns')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_campaigns', to='api.product')),
            ],
            options={
                'db_table': 'Campaign_Product',
                'unique_together': {('campaign', 'product')},
            },
        ),
    ]
