# Generated by Django 6.0.3 on 2026-06-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_campaigns_order_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admins",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("vendor_id", models.CharField(db_column="Vendor_id", max_length=100)),
                ("product_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("discounted_price", models.IntegerField(blank=True, null=True)),
                ("stock", models.IntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("vendor_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("tax_id", models.CharField(db_column="Tax_ID", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "detail_address",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminAuditLogs",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("action_type", models.CharField(max_length=100)),
                (
                    "submission_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tasks_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "influencer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vendor_id", models.CharField(blank=True, max_length=100, null=True)),
                ("action_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_id",
                    models.ForeignKey(
                        db_column="Admin_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.admins",
                    ),
                ),
            ],
            options={
                "db_table": "Admin_Audit_Logs",
            },
        ),
        migrations.CreateModel(
            name="CampaignApplications",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=50)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        db_column="Campaign_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.campaigns",
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        db_column="Influencer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "Campaign_applications",
            },
        ),
        migrations.CreateModel(
            name="CampaignParticipants",
            fields=[
                (
                    "participants_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "assigned_coupon_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(max_length=50)),
                (
                    "campaign",
                    models.ForeignKey(
                        db_column="Campaign_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.campaigns",
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        db_column="Influencer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "Campaign_Participants",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=50)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commissions",
            fields=[
                ("commission_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        db_column="Influencer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="Order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "promotion_code",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=50)),
                (
                    "campaign",
                    models.ForeignKey(
                        db_column="campaign_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.campaigns",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("guest_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "order_id",
                    models.ForeignKey(
                        db_column="Order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KOCMission",
            fields=[
                (
                    "kocmission_id",
                    models.AutoField(
                        db_column="KOCMission_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "mission_id",
                    models.CharField(db_column="Mission_id", max_length=100),
                ),
                ("stage", models.CharField(max_length=50)),
                (
                    "promotion_code",
                    models.ForeignKey(
                        blank=True,
                        db_column="Promotion_code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.coupon",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="User_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="Product_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.product",
                    ),
                ),
                (
                    "brand_id",
                    models.ForeignKey(
                        db_column="Brand_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "KOC_Mission",
            },
        ),
        migrations.CreateModel(
            name="Earnings",
            fields=[
                ("earnings_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="User_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
                (
                    "kocmission_id",
                    models.ForeignKey(
                        db_column="KOCMission_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.kocmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissionTasks",
            fields=[
                ("tasks_id", models.AutoField(primary_key=True, serialize=False)),
                ("deadline", models.DateTimeField()),
                ("status", models.CharField(max_length=50)),
                ("stage", models.CharField(max_length=50)),
                (
                    "kocmission_id",
                    models.ForeignKey(
                        db_column="KOCMission_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.kocmission",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="User_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "Mission_Tasks",
            },
        ),
        migrations.CreateModel(
            name="Drafts",
            fields=[
                ("drafts_id", models.AutoField(primary_key=True, serialize=False)),
                ("version_number", models.IntegerField()),
                ("text_content", models.TextField(blank=True, null=True)),
                ("media_urls", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("brand_feedback", models.TextField(blank=True, null=True)),
                ("submitted_time", models.DateTimeField(blank=True, null=True)),
                ("reviewed_time", models.DateTimeField(blank=True, null=True)),
                (
                    "kocmission_id",
                    models.ForeignKey(
                        db_column="KOCMission_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.kocmission",
                    ),
                ),
                (
                    "tasks_id",
                    models.ForeignKey(
                        db_column="Tasks_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.missiontasks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "promotion_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        db_column="Order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payouts",
            fields=[
                ("payout_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("payout_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
                (
                    "influencer_id",
                    models.ForeignKey(
                        db_column="Influencer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("cart_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.IntegerField()),
                ("subtotal", models.IntegerField()),
                (
                    "cart_id",
                    models.ForeignKey(
                        db_column="cart_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cart",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackingLogs",
            fields=[
                ("tracking_id", models.AutoField(primary_key=True, serialize=False)),
                ("click_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        db_column="Promotion_code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="Order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="User_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "Tracking_logs",
            },
        ),
        migrations.CreateModel(
            name="ServiceTickets",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("resolution_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="Admin_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.admins",
                    ),
                ),
                (
                    "consumer_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="Consumer_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_as_consumer",
                        to="api.user",
                    ),
                ),
                (
                    "influencer_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="Influencer_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_as_influencer",
                        to="api.user",
                    ),
                ),
                (
                    "kocmission_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="KOCMission_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.kocmission",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="Order_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.order",
                    ),
                ),
                (
                    "vendor_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="Vendor_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "Service_Tickets",
            },
        ),
        migrations.CreateModel(
            name="MissionApplication",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mission_id",
                    models.CharField(db_column="Mission_id", max_length=100),
                ),
                ("status", models.CharField(max_length=50)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="User_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
                (
                    "brand_id",
                    models.ForeignKey(
                        db_column="Brand_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "Mission_Application",
            },
        ),
        migrations.CreateModel(
            name="VendorWallet",
            fields=[
                (
                    "wallet_id",
                    models.AutoField(
                        db_column="Wallet_id", primary_key=True, serialize=False
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("history", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor_id",
                    models.ForeignKey(
                        db_column="Vendor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "Vendor_Wallet",
            },
        ),
        migrations.CreateModel(
            name="Wallets",
            fields=[
                ("wallets_id", models.AutoField(primary_key=True, serialize=False)),
                ("balance_available", models.IntegerField(default=0)),
                ("balance_frozen", models.IntegerField(default=0)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "transaction_id",
                    models.AutoField(
                        db_column="Transaction_ID", primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(db_column="Type", max_length=50)),
                ("amount", models.IntegerField(db_column="Amount")),
                (
                    "reference_type",
                    models.CharField(db_column="Reference_type", max_length=50),
                ),
                (
                    "reference_id",
                    models.CharField(db_column="Reference_id", max_length=100),
                ),
                (
                    "wallets_id",
                    models.ForeignKey(
                        db_column="Wallets_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.wallets",
                    ),
                ),
            ],
            options={
                "db_table": "Transactions",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("wishlist_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkSubmissions",
            fields=[
                ("submission_id", models.AutoField(primary_key=True, serialize=False)),
                ("version_number", models.IntegerField()),
                (
                    "content_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("status", models.CharField(max_length=50)),
                ("brand_feedback", models.TextField(blank=True, null=True)),
                ("submitted_time", models.DateTimeField(blank=True, null=True)),
                ("reviewed_time", models.DateTimeField(blank=True, null=True)),
                (
                    "kocmission_id",
                    models.ForeignKey(
                        db_column="KOCMission_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.kocmission",
                    ),
                ),
                (
                    "tasks_id",
                    models.ForeignKey(
                        db_column="Tasks_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.missiontasks",
                    ),
                ),
            ],
            options={
                "db_table": "Work_Submissions",
            },
        ),
    ]
