# Generated by Django 6.0.3 on 2026-06-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_campaigns_product_id_campaignproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='koc',
            field=models.ForeignKey(blank=True, db_column='koc_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.koc'),
        ),
        migrations.AddField(
            model_name='application',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.order'),
        ),
        migrations.AlterField(
            model_name='application',
            name='campaign',
            field=models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.campaigns'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=50),
        ),
    ]
