# Generated by Django 6.0.3 on 2026-07-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vendor_vendor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kocmission', models.OneToOneField(db_column='kocmission_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='api.kocmissionnew')),
            ],
            options={
                'db_table': 'ChatRoom',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('koc', 'KOC'), ('vendor', '廠商')], db_column='sender_role', max_length=20)),
                ('sender_id', models.CharField(db_column='sender_id', max_length=50)),
                ('content', models.TextField(db_column='content')),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom')),
            ],
            options={
                'db_table': 'Message',
                'ordering': ['created_at'],
            },
        ),
    ]
