# Generated by Django 6.0.3 on 2026-07-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='discount_percent',
            field=models.IntegerField(db_column='discount_percent', default=0),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='promo_days',
            field=models.IntegerField(db_column='promo_days', default=7),
        ),
    ]