# Generated by Django 6.0.3 on 2026-06-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_application_user_application_koc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(db_column='product_id', default='1', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.product'),
            preserve_default=False,
        ),
    ]
