# Generated by Django 6.0.3 on 2026-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_campaigns_discount_percent_campaigns_promo_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已通過'), ('rejected', '已拒絕')], db_column='status', default='pending', max_length=20),
        ),

    ]

