# Generated by Django 6.0.3 on 2026-06-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_orderitem_product_id_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='earnings',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='payouts',
            old_name='koc_id',
            new_name='koc',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
