# Generated by Django 6.0.3 on 2026-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='discount_type',
            field=models.CharField(choices=[('percentage', '百分比折扣'), ('fixed', '直接折價')], db_column='discount_type', default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='discount_value',
            field=models.DecimalField(db_column='discount_value', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='koc_commission_rate',
            field=models.DecimalField(db_column='koc_commission_rate', decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='couponnew',
            name='discount_type',
            field=models.CharField(choices=[('percentage', '百分比折扣'), ('fixed', '直接折價')], db_column='discount_type', default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='couponnew',
            name='koc_commission_rate',
            field=models.DecimalField(db_column='koc_commission_rate', decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='couponnew',
            name='discount_value',
            field=models.DecimalField(db_column='discount_value', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='couponnew',
            name='total_commission',
            field=models.DecimalField(db_column='total_commission', decimal_places=2, default=0, max_digits=12),
        ),
    ]
