# Generated by Django 6.0.3 on 2026-06-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_address_user_rename_user_id_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminauditlogs',
            name='koc_id',
        ),
        migrations.RemoveField(
            model_name='adminauditlogs',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='campaignparticipants',
            name='assigned_coupon_id',
        ),
        migrations.RemoveField(
            model_name='campaignparticipants',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='order',
        ),
        migrations.RemoveField(
            model_name='kocmissionnew',
            name='koc_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guest_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='wallet_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='wallet_type',
        ),
        migrations.AddField(
            model_name='adminauditlogs',
            name='koc',
            field=models.ForeignKey(blank=True, db_column='koc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.koc'),
        ),
        migrations.AddField(
            model_name='adminauditlogs',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='api.vendor'),
        ),
        migrations.AddField(
            model_name='campaignparticipants',
            name='coupon',
            field=models.ForeignKey(blank=True, db_column='coupon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_participants', to='api.couponnew'),
        ),
        migrations.AddField(
            model_name='campaignparticipants',
            name='koc',
            field=models.ForeignKey(db_column='koc_id', default='1', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigns',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', default='1', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kocmissionnew',
            name='koc',
            field=models.ForeignKey(blank=True, db_column='koc_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.koc'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(blank=True, db_column='guest_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.guest'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='koc_wallet',
            field=models.ForeignKey(blank=True, db_column='koc_wallet_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.kocwallet'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='vendor_wallet',
            field=models.ForeignKey(blank=True, db_column='vendor_wallet_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.vendorwallet'),
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('koc_wallet__isnull', False), ('vendor_wallet__isnull', True)), models.Q(('koc_wallet__isnull', True), ('vendor_wallet__isnull', False)), _connector='OR'), name='transactions_exactly_one_wallet'),
        ),
    ]
