# Generated by Django 6.0.3 on 2026-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_adminauditlogs_koc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='status',
            field=models.CharField(choices=[('pending', '審核中'), ('revising', '修改中'), ('approved', '審核通過')], db_column='status', default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submission_type',
            field=models.CharField(choices=[('text', '文案'), ('link', '作品連結')], db_column='submission_type', max_length=50),
        ),
    ]
