# Generated by Django 6.0.3 on 2026-07-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_address_recipient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='couponnew',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='couponnew',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='couponnew',
            name='koc_commission_rate',
        ),
        migrations.RemoveField(
            model_name='couponnew',
            name='total_commission',
        ),
    ]
