# Generated by Django 6.0.3 on 2026-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_submissions_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponnew',
            name='status',
            field=models.CharField(choices=[('inactive', '未啟用'), ('active', '啟用中'), ('expired', '已過期')], db_column='status', default='inactive', max_length=50),
        ),
    ]
