# Generated by Django 6.0.3 on 2026-07-08 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_couponnew_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactions',
            name='transactions_exactly_one_wallet',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='earnings',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payouts',
            old_name='koc',
            new_name='koc_id',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='adminauditlogs',
            name='koc',
        ),
        migrations.RemoveField(
            model_name='adminauditlogs',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='application',
            name='koc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='order',
        ),
        migrations.RemoveField(
            model_name='campaignparticipants',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='campaignparticipants',
            name='koc',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='kocmissionnew',
            name='koc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='adminauditlogs',
            name='koc_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlogs',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='koc_id',
            field=models.CharField(blank=True, db_column='koc_id', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='order_id',
            field=models.UUIDField(blank=True, db_column='order_id', null=True),
        ),
        migrations.AddField(
            model_name='campaignparticipants',
            name='assigned_coupon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaignparticipants',
            name='influencer',
            field=models.ForeignKey(blank=True, db_column='influencer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(blank=True, db_column='cart_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cart'),
        ),
        migrations.AddField(
            model_name='guest',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AddField(
            model_name='kocmissionnew',
            name='koc_id',
            field=models.CharField(blank=True, db_column='koc_id', db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallet_type',
            field=models.CharField(default='koc', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='campaign',
            field=models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='api.campaigns'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(db_column='status', max_length=50),
        ),
        migrations.AlterField(
            model_name='couponnew',
            name='status',
            field=models.CharField(db_column='status', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='status',
            field=models.CharField(db_column='status', max_length=50),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submission_type',
            field=models.CharField(db_column='submission_type', max_length=50),
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='koc_wallet',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='vendor_wallet',
        ),
    ]
