# Generated by Django 6.0.3 on 2026-06-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_couponnew_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='kocmission',
            field=models.ForeignKey(blank=True, db_column='kocmission_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='api.kocmissionnew'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='status',
            field=models.CharField(choices=[('pending', '待定'), ('withdrawable', '可提領')], default='pending', max_length=50),
        ),
    ]
