# Generated by Django 6.0.3 on 2026-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_campaigns_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reject_reason',
            field=models.TextField(blank=True, db_column='reject_reason', null=True),
        ),
    ]
