# Generated by Django 6.0.3 on 2026-07-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_earnings_kocmission_alter_earnings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='status',
            field=models.CharField(choices=[('pending', '待定'), ('withdrawable', '可提領'), ('transferred', '已轉帳')], default='pending', max_length=50),
        ),
    ]
