# Generated by Django 6.0.3 on 2026-08-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_application_created_at"),
        ("api", "0011_wishlist_unique_wishlist_user_product"),
    ]

    operations = []
