# Generated by Django 6.0.3 on 2026-07-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_earnings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earnings',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='api.order'),
        ),
    ]
