# Generated by Django 6.0.3 on 2026-08-08 08:41
# 這兩個欄位在資料庫裡其實已經存在（不知道是誰在別的地方手動加的，
# migration history 沒有紀錄），這支只是把 migration 狀態補齊，用 --fake 套用。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260804_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='koc',
            name='ig_url',
            field=models.CharField(blank=True, db_column='ig_url', default='', max_length=300),
        ),
        migrations.AddField(
            model_name='koc',
            name='threads_url',
            field=models.CharField(blank=True, db_column='threads_url', default='', max_length=300),
        ),
    ]
