# Generated by Django 6.0.3 on 2026-08-09 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_merge_20260804_2058"),
    ]

    operations = [
        migrations.AddField(
            model_name="koc",
            name="fb_url",
            field=models.CharField(
                blank=True, db_column="fb_url", default="", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="koc",
            name="ig_url",
            field=models.CharField(
                blank=True, db_column="ig_url", default="", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="koc",
            name="threads_url",
            field=models.CharField(
                blank=True, db_column="threads_url", default="", max_length=300
            ),
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("ip_address", models.CharField(blank=True, max_length=50, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "db_table": "Login_History",
                "ordering": ["-login_at"],
            },
        ),
    ]
