# Generated by Django 6.0.3 on 2026-07-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_earnings_created_at_earnings_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '審核中'), ('revising', '修改中'), ('approved', '審核通過')], db_column='status', default='pending', max_length=50),
        ),
    ]
