# Generated by Django 6.0.3 on 2026-08-08 08:41
# 這兩個欄位在資料庫裡其實已經存在（不知道是誰在別的地方手動加的，
# migration history 沒有紀錄），這支只是把 migration 狀態補齊，用 --fake 套用。
#
# 2026-10-01 補充：同一天另一條分支的 0013_koc_fb_url_koc_ig_url_koc_threads_url_loginhistory
# 也會真的新增 ig_url / threads_url 這兩個欄位，兩支都依賴同一個 0012，等於兩邊都要加同樣的欄位。
# 在正式雲端資料庫上因為這支本來就是用 --fake 套用（沒有真的執行過 SQL），所以不影響正式環境；
# 但如果要從零建一個全新資料庫（例如跑 `manage.py test`），兩支都真的執行就會撞成
# 「Duplicate column name 'ig_url'」。改成空的 operations，讓新增欄位這件事只交給
# 0013_koc_fb_url_koc_ig_url_koc_threads_url_loginhistory 做一次就好。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260804_2058'),
    ]

    operations = []
