# Generated by Django 6.0.3 on 2026-08-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_koc_fb_url_koc_ig_url_koc_threads_url_loginhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_updated_at",
            field=models.DateTimeField(
                blank=True, db_column="password_updated_at", null=True
            ),
        ),
    ]
