# Generated by Django 6.0.3 on 2026-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_submissions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='koc',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已通過'), ('rejected', '已拒絕')], db_column='approval_status', default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='koc',
            name='reject_reason',
            field=models.TextField(blank=True, db_column='reject_reason', null=True),
        ),
    ]
