# Generated by Django 6.0.3 on 2026-07-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_koc_approval_status_koc_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koc',
            name='bank_account',
            field=models.CharField(blank=True, db_column='bank_account', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='koc',
            name='bank_number',
            field=models.CharField(blank=True, db_column='bank_number', default='', max_length=50),
        ),
    ]
