# Generated by Django 6.0.3 on 2026-08-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('verification_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to='api.user')),
            ],
            options={
                'db_table': 'EmailVerificationCode',
            },
        ),
    ]
