# Generated by Django 6.0.3 on 2026-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_koc_bank_account_alter_koc_bank_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koc',
            name='social_account',
        ),
        migrations.AddField(
            model_name='koc',
            name='fb_account',
            field=models.CharField(blank=True, db_column='fb_account', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='koc',
            name='ig_account',
            field=models.CharField(blank=True, db_column='ig_account', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='koc',
            name='threads_account',
            field=models.CharField(blank=True, db_column='threads_account', default='', max_length=100),
        ),
    ]
