# Generated by Django 6.0.3 on 2026-08-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_user_password_updated_at"),
        ("api", "0015_user_is_verified_emailverificationcode"),
    ]

    operations = []
