# Generated by Django 6.0.3 on 2026-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_koc_social_account_koc_fb_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='koc',
            name='is_suspended',
            field=models.BooleanField(db_column='is_suspended', default=False),
        ),
    ]
