# Generated by Django 6.0.3 on 2026-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_submissions_ai_result_alter_couponnew_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ad_category",
            field=models.CharField(
                choices=[
                    ("food", "食品"),
                    ("cosmetic", "化粧品"),
                    ("medical_device", "醫療器材"),
                    ("drug", "藥品"),
                    ("other", "其他"),
                ],
                db_column="ad_category",
                default="other",
                max_length=20,
            ),
        ),
    ]
