# Generated by Django 6.0.3 on 2026-08-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_ad_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentInfo',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(default='ecpay', max_length=20)),
                ('logistics_type', models.CharField(default='CVS', max_length=20)),
                ('logistics_sub_type', models.CharField(default='UNIMARTC2C', max_length=30)),
                ('store_id', models.CharField(blank=True, max_length=20, null=True)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_address', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_trade_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ecpay_logistics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_info', to='api.order')),
            ],
            options={
                'db_table': 'Shipment_Info',
            },
        ),
    ]
