# Generated by Django 6.0.3 on 2026-08-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_shipmentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentinfo',
            name='cvs_payment_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipmentinfo',
            name='cvs_validation_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
