# Generated by Django 6.0.3 on 2026-08-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_vendor_sender_address_vendor_sender_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentinfo',
            name='booking_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
