# Generated by Django 6.0.3 on 2026-08-24 15:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_shipmentinfo_booking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_column='delivered_at', null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='fee_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='gross_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account',
            field=models.CharField(blank=True, db_column='bank_account', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_name',
            field=models.CharField(blank=True, db_column='bank_account_name', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_code',
            field=models.CharField(blank=True, db_column='bank_code', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='platform_fee_rate',
            field=models.DecimalField(db_column='platform_fee_rate', decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.CreateModel(
            name='VendorPayouts',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payout_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, to='api.vendor')),
            ],
            options={
                'db_table': 'Vendor_Payouts',
            },
        ),
    ]
