# Generated by Django 6.0.3 on 2026-08-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_delivered_at_transactions_fee_amount_and_more'),
        ('api', '0023_vendor_is_verified_vendoremailverificationcode'),
    ]

    operations = [
    ]
