# Generated by Django 6.0.3 on 2026-08-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_merge_20260825_1316"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(
                blank=True, db_column="invoice_number", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_uploaded_at",
            field=models.DateTimeField(
                blank=True, db_column="invoice_uploaded_at", null=True
            ),
        ),
        migrations.CreateModel(
            name="VendorInvoice",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "relate_number",
                    models.CharField(
                        db_column="relate_number", max_length=20, unique=True
                    ),
                ),
                (
                    "settlement_amount",
                    models.DecimalField(
                        db_column="settlement_amount", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        db_column="service_fee", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        db_column="tax_amount", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        db_column="total_amount", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待開立"),
                            ("issued", "開立成功"),
                            ("failed", "開立失敗"),
                        ],
                        db_column="status",
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, db_column="invoice_number", max_length=20, null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, db_column="error_message", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        db_column="vendor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="api.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "Vendor_Invoice",
            },
        ),
    ]
