# Generated by Django 6.0.3 on 2026-08-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20260825_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_rejected_at',
            field=models.DateTimeField(blank=True, db_column='cancel_rejected_at', null=True),
        ),
    ]
