# Generated by Django 6.0.3 on 2026-08-27 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20260825_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='original_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_column='completed_at', null=True),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='status',
            field=models.CharField(choices=[('pending', '待定'), ('withdrawable', '可提領'), ('transferred', '已轉帳'), ('cancelled', '已取消')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('return_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('defective', '商品瑕疵'), ('mismatched', '商品與描述不符'), ('wrong_size', '尺寸不合'), ('no_longer_needed', '不符合需求'), ('other', '其他')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', '申請中'), ('approved', '已同意'), ('rejected', '已拒絕'), ('disputed', '爭議中'), ('returning', '商品退回中'), ('received', '廠商已收貨'), ('refunding', '退款處理中'), ('refunded', '退款完成'), ('cancelled', '消費者自行取消申請')], default='requested', max_length=50)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_note', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('ecpay_refund_trade_no', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_disputes', to='api.admins')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='api.order')),
                ('order_item', models.ForeignKey(blank=True, db_column='order_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='api.orderitem')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='api.user')),
            ],
            options={
                'db_table': 'Return_Request',
            },
        ),
        migrations.AddField(
            model_name='earnings',
            name='cancelled_by_return_request',
            field=models.ForeignKey(blank=True, db_column='cancelled_by_return_request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_earnings', to='api.returnrequest'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='Return_Requ_order_i_b737ea_idx'),
        ),
    ]
