# Generated by Django 6.0.3 on 2026-08-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_cancel_rejected_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChatRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('vendor', '廠商'), ('user', '消費者')], db_column='participant_type', max_length=20)),
                ('participant_id', models.CharField(db_column='participant_id', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SupportChatRoom',
                'unique_together': {('participant_type', 'participant_id')},
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('vendor', '廠商'), ('user', '消費者'), ('admin', '客服')], db_column='sender_role', max_length=20)),
                ('sender_id', models.CharField(db_column='sender_id', max_length=50)),
                ('content', models.TextField(db_column='content')),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.supportchatroom')),
            ],
            options={
                'db_table': 'SupportMessage',
                'ordering': ['created_at'],
            },
        ),
    ]
