# Generated by Django 6.0.3 on 2026-08-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_supportchatroom_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemunerationForm',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_review', '待審核'), ('approved', '審核通過'), ('rejected', '已退回')], db_column='status', default='pending_review', max_length=20)),
                ('cloud_link_url', models.URLField(db_column='cloud_link_url', max_length=500)),
                ('submitted_at', models.DateTimeField(db_column='submitted_at')),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', null=True)),
                ('reviewed_by_admin_id', models.CharField(blank=True, db_column='reviewed_by_admin_id', max_length=50, null=True)),
                ('reject_reason', models.TextField(blank=True, db_column='reject_reason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kocmission', models.OneToOneField(db_column='kocmission_id', on_delete=django.db.models.deletion.CASCADE, related_name='remuneration_form', to='api.kocmissionnew')),
            ],
            options={
                'db_table': 'RemunerationForm',
            },
        ),
    ]
