# Generated by Django 6.0.3 on 2026-08-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remunerationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, db_column='cancel_reason', null=True),
        ),
    ]
