# Generated by Django 6.0.3 on 2026-08-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_invoice_number_order_invoice_uploaded_at_and_more'),
        ('api', '0028_order_cancel_reason'),
    ]

    operations = [
    ]
