# Generated by Django 6.0.3 on 2026-09-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_earnings_original_amount_order_completed_at_and_more"),
        ("api", "0030_order_shipping_fee"),
    ]

    operations = []
