# Generated by Django 6.0.3 on 2026-09-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_order_shipping_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChatRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='api.order')),
            ],
            options={
                'db_table': 'OrderChatRoom',
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('user', '消費者'), ('vendor', '廠商')], db_column='sender_role', max_length=20)),
                ('sender_id', models.CharField(db_column='sender_id', max_length=50)),
                ('content', models.TextField(db_column='content')),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.orderchatroom')),
            ],
            options={
                'db_table': 'OrderMessage',
                'ordering': ['created_at'],
            },
        ),
    ]
