# Generated by Django 6.0.3 on 2026-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_merge_20260901_2036"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="quantity",
            field=models.IntegerField(blank=True, db_column="quantity", null=True),
        ),
    ]
