# Generated by Django 6.0.3 on 2026-09-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_returnrequest_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="packing_proof_uploaded_at",
            field=models.DateTimeField(
                blank=True, db_column="packing_proof_uploaded_at", null=True
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="packing_proof_urls",
            field=models.JSONField(
                blank=True, db_column="packing_proof_urls", default=list
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="vendor_dispute_deadline",
            field=models.DateTimeField(
                blank=True, db_column="vendor_dispute_deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="vendor_dispute_description",
            field=models.TextField(
                blank=True, db_column="vendor_dispute_description", null=True
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="vendor_dispute_photo_urls",
            field=models.JSONField(
                blank=True, db_column="vendor_dispute_photo_urls", default=list
            ),
        ),
    ]
