# Generated by Django 6.0.3 on 2026-09-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remuneration_form_aggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('order', '訂單'), ('koc', 'KOC接案')], db_column='category', max_length=20)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('body', models.TextField(blank=True, db_column='body', default='')),
                ('reference_type', models.CharField(blank=True, db_column='reference_type', max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, db_column='reference_id', max_length=100, null=True)),
                ('is_read', models.BooleanField(db_column='is_read', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.user')),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
