# Generated by Django 6.0.3 on 2026-09-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_returnrequest_packing_proof_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissions",
            name="revising_deadline",
            field=models.DateTimeField(
                blank=True, db_column="revising_deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="submissions",
            name="revising_reminder_sent",
            field=models.BooleanField(
                db_column="revising_reminder_sent", default=False
            ),
        ),
    ]
