# Generated by Django 6.0.3 on 2026-09-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='kocmissionnew',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('expired', '已過期'), ('cancelled', 'KOC取消')], db_column='end_reason', max_length=20, null=True),
        ),
    ]
