# Generated by Django 6.0.3 on 2026-09-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_submissions_revising_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="last_review_reminder_batch_time",
            field=models.DateTimeField(
                blank=True, db_column="last_review_reminder_batch_time", null=True
            ),
        ),
    ]
