# Generated by Django 6.0.3 on 2026-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_kocmissionnew_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='koc',
            name='suspended_until',
            field=models.DateTimeField(blank=True, db_column='suspended_until', null=True),
        ),
    ]
