# Generated by Django 6.0.3 on 2026-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_vendor_last_review_reminder_batch_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigns",
            name="recruit_limit",
            field=models.IntegerField(blank=True, db_column="recruit_limit", null=True),
        ),
    ]
