# Generated by Django 6.0.3 on 2026-09-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_koc_suspended_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='koc',
            name='cancel_count_since_suspension',
            field=models.IntegerField(db_column='cancel_count_since_suspension', default=0),
        ),
        migrations.AddField(
            model_name='koc',
            name='total_cancel_count',
            field=models.IntegerField(db_column='total_cancel_count', default=0),
        ),
    ]
