# Generated by Django 6.0.3 on 2026-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_campaigns_recruit_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="kocmissionnew",
            name="missed_publishing_deadline",
            field=models.BooleanField(
                db_column="missed_publishing_deadline", default=False
            ),
        ),
        migrations.AddField(
            model_name="kocmissionnew",
            name="publishing_started_at",
            field=models.DateTimeField(
                blank=True, db_column="publishing_started_at", null=True
            ),
        ),
    ]
