# Generated by Django 6.0.3 on 2026-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_koc_violation_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koc',
            name='total_violation_count',
            field=models.IntegerField(db_column='total_violation_count', default=0),
        ),
        migrations.AlterField(
            model_name='koc',
            name='violation_count_since_suspension',
            field=models.IntegerField(db_column='violation_count_since_suspension', default=0),
        ),
    ]
