# Generated by Django 6.0.3 on 2026-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_koc_total_violation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kocmissionnew',
            name='submission_deadline_at',
            field=models.DateTimeField(blank=True, db_column='submission_deadline_at', null=True),
        ),
        migrations.AddField(
            model_name='kocmissionnew',
            name='submission_reminder_sent',
            field=models.BooleanField(db_column='submission_reminder_sent', default=False),
        ),
    ]
