# Generated by Django 6.0.3 on 2026-09-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_campaigns_recruit_limit'),
        ('api', '0040_kocmissionnew_submission_deadline_at_and_more'),
    ]

    operations = [
    ]
