# Generated by Django 6.0.3 on 2026-09-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_kocmissionnew_missed_publishing_deadline_and_more"),
        ("api", "0041_merge_20260914_0142"),
    ]

    operations = []
