# Generated by Django 6.0.3 on 2026-09-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_merge_20260914_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouts',
            name='platform_fee',
            field=models.IntegerField(db_column='platform_fee', default=0),
        ),
    ]
