# Generated by Django 6.0.3 on 2026-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_merge_20260914_1852"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_returnable",
            field=models.BooleanField(db_column="is_returnable", default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="non_returnable_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("perishable", "易腐敗、保存期限較短，或退貨時將逾期"),
                    ("customized", "客製化商品、服務"),
                    ("periodical", "報紙、期刊或雜誌"),
                    ("opened_media", "經拆封的影音商品或電腦軟體"),
                    (
                        "digital_content",
                        "經消費者同意而提供的非有形媒介數位內容或提供即完成的線上服務",
                    ),
                    ("opened_hygiene", "已拆封的個人衛生用品"),
                    ("air_transport", "國際航空客運服務"),
                ],
                db_column="non_returnable_reason",
                max_length=30,
                null=True,
            ),
        ),
    ]
