# Generated by Django 6.0.3 on 2026-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_payouts_platform_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouts',
            name='invoice_number',
            field=models.CharField(blank=True, db_column='invoice_number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payouts',
            name='invoice_uploaded_at',
            field=models.DateTimeField(blank=True, db_column='invoice_uploaded_at', null=True),
        ),
    ]
