# Generated by Django 6.0.3 on 2026-09-15 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_product_is_returnable_product_non_returnable_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.vendor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('order', '訂單'), ('koc', 'KOC接案'), ('return', '退貨'), ('payout', '撥款')], db_column='category', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.user'),
        ),
    ]
