# Generated by Django 6.0.3 on 2026-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_product_is_returnable_product_non_returnable_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorinvoice",
            name="koc_commission_display",
            field=models.DecimalField(
                blank=True,
                db_column="koc_commission_display",
                decimal_places=2,
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendorinvoice",
            name="platform_service_fee",
            field=models.DecimalField(
                blank=True,
                db_column="platform_service_fee",
                decimal_places=2,
                max_digits=12,
                null=True,
            ),
        ),
    ]
