# Generated by Django 6.0.3 on 2026-09-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_payouts_invoice_number_payouts_invoice_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouts',
            name='random_number',
            field=models.CharField(blank=True, db_column='random_number', max_length=10, null=True),
        ),
    ]
