# Generated by Django 6.0.3 on 2026-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_vendorinvoice_koc_commission_display_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="koc_commission_fee_display",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="platform_fee_display",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
