# Generated by Django 6.0.3 on 2026-09-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_transactions_koc_commission_fee_display_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="ecpay_return_order_no",
            field=models.CharField(
                blank=True, db_column="ecpay_return_order_no", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="ecpay_return_trade_no",
            field=models.CharField(
                blank=True, db_column="ecpay_return_trade_no", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="return_ship_deadline",
            field=models.DateTimeField(
                blank=True, db_column="return_ship_deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="return_ship_expired",
            field=models.BooleanField(db_column="return_ship_expired", default=False),
        ),
    ]
