# Generated by Django 6.0.3 on 2026-09-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_notification_vendor_alter_notification_category_and_more"),
        ("api", "0045_transactions_koc_commission_fee_display_and_more"),
    ]

    operations = []
