# Generated by Django 6.0.3 on 2026-09-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_payouts_random_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouts',
            name='invoice_issued_automatically',
            field=models.BooleanField(db_column='invoice_issued_automatically', default=False),
        ),
        migrations.AddField(
            model_name='payouts',
            name='invoice_voided_at',
            field=models.DateTimeField(blank=True, db_column='invoice_voided_at', null=True),
        ),
    ]
