# Generated by Django 6.0.3 on 2026-09-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_returnrequest_ecpay_return_order_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnrequest",
            name="ecpay_return_order_no",
            field=models.CharField(
                blank=True, db_column="ecpay_return_order_no", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="ecpay_return_trade_no",
            field=models.CharField(
                blank=True, db_column="ecpay_return_trade_no", max_length=30, null=True
            ),
        ),
    ]
