# Generated by Django 6.0.3 on 2026-09-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_merge_20260915_1950'),
        ('api', '0046_payouts_invoice_issued_automatically_and_more'),
    ]

    operations = [
    ]
