# Generated by Django 6.0.3 on 2026-09-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_returnrequest_ecpay_return_order_no_and_more"),
        ("api", "0047_merge_20260915_2022"),
    ]

    operations = []
