# Generated by Django 6.0.3 on 2026-09-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_merge_20260921_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payouts',
            name='invoice_issued_automatically',
        ),
        migrations.RemoveField(
            model_name='payouts',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='payouts',
            name='invoice_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='payouts',
            name='invoice_voided_at',
        ),
        migrations.RemoveField(
            model_name='payouts',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='payouts',
            name='random_number',
        ),
    ]
