# Generated by Django 6.0.3 on 2026-09-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_payouts_invoice_issued_automatically_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponnew',
            name='click_count',
            field=models.IntegerField(db_column='click_count', default=0),
        ),
        migrations.CreateModel(
            name='KocLinkClickDaily',
            fields=[
                ('click_id', models.AutoField(db_column='click_id', primary_key=True, serialize=False)),
                ('click_date', models.DateField(db_column='click_date')),
                ('click_count', models.IntegerField(db_column='click_count', default=0)),
                ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_clicks', to='api.couponnew')),
            ],
            options={
                'db_table': 'Koc_Link_Click_Daily',
                'unique_together': {('coupon', 'click_date')},
            },
        ),
    ]
