# Generated by Django 6.0.3 on 2026-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_couponnew_click_count_koclinkclickdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='remittance_account_last5',
            field=models.CharField(blank=True, db_column='remittance_account_last5', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='remittance_amount',
            field=models.IntegerField(blank=True, db_column='remittance_amount', null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='remittance_confirmed_at',
            field=models.DateTimeField(blank=True, db_column='remittance_confirmed_at', null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='remittance_date',
            field=models.DateField(blank=True, db_column='remittance_date', null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='remittance_reject_reason',
            field=models.TextField(blank=True, db_column='remittance_reject_reason', null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='remittance_reported_at',
            field=models.DateTimeField(blank=True, db_column='remittance_reported_at', null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='status',
            field=models.CharField(choices=[('awaiting_remittance', '待廠商匯款'), ('remittance_reported', '廠商已回報，待確認'), ('issued', '開立成功'), ('rejected', '匯款回報已退回'), ('failed', '開立失敗')], db_column='status', default='awaiting_remittance', max_length=20),
        ),
    ]
