# Generated by Django 6.0.3 on 2026-10-01 06:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_couponnew_click_count_koclinkclickdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSettlement',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_column='period_start')),
                ('period_end', models.DateField(db_column='period_end')),
                ('gross_sales', models.DecimalField(db_column='gross_sales', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('adjustment_amount', models.DecimalField(db_column='adjustment_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settlement_rate', models.DecimalField(db_column='settlement_rate', decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('amount_due', models.DecimalField(db_column='amount_due', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('koc_amount', models.DecimalField(db_column='koc_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('platform_amount', models.DecimalField(db_column='platform_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', '結算中'), ('awaiting_payment', '待繳款'), ('partially_paid', '部分繳款'), ('paid', '已繳清'), ('overdue', '已逾期'), ('cancelled', '已取消')], db_column='status', default='draft', max_length=30)),
                ('due_date', models.DateField(blank=True, db_column='due_date', null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_column='paid_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='api.vendor')),
            ],
            options={
                'db_table': 'Vendor_Settlement',
            },
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='settlement',
            field=models.ForeignKey(blank=True, db_column='settlement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.vendorsettlement'),
        ),
        migrations.CreateModel(
            name='VendorSettlementItem',
            fields=[
                ('settlement_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_amount', models.DecimalField(db_column='sales_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settlement_rate', models.DecimalField(db_column='settlement_rate', decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('settlement_amount', models.DecimalField(db_column='settlement_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('koc_amount', models.DecimalField(db_column='koc_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('platform_amount', models.DecimalField(db_column='platform_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', '等待結算資格'), ('eligible', '可納入結算'), ('included', '已納入結算'), ('refunded', '已退款'), ('cancelled', '已取消'), ('adjusted', '已調整')], db_column='status', default='pending', max_length=30)),
                ('eligible_at', models.DateTimeField(blank=True, db_column='eligible_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_settlement_items', to='api.order')),
                ('settlement', models.ForeignKey(blank=True, db_column='settlement_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='api.vendorsettlement')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='api.vendor')),
            ],
            options={
                'db_table': 'Vendor_Settlement_Item',
            },
        ),
        migrations.CreateModel(
            name='VendorSettlementPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('bank_transfer', '銀行轉帳'), ('manual', '人工入帳'), ('other', '其他')], db_column='payment_method', default='bank_transfer', max_length=30)),
                ('reference_no', models.CharField(blank=True, db_column='reference_no', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('failed', '入帳失敗'), ('cancelled', '已取消')], db_column='status', default='pending', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, db_column='paid_at', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_column='confirmed_at', null=True)),
                ('note', models.TextField(blank=True, db_column='note', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='confirmed_by_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_vendor_settlement_payments', to='api.admins')),
                ('settlement', models.ForeignKey(db_column='settlement_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.vendorsettlement')),
            ],
            options={
                'db_table': 'Vendor_Settlement_Payment',
            },
        ),
        migrations.AddIndex(
            model_name='vendorsettlement',
            index=models.Index(fields=['vendor', 'status'], name='idx_vendor_settle_status'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlement',
            index=models.Index(fields=['period_start', 'period_end'], name='idx_vendor_settle_period'),
        ),
        migrations.AddConstraint(
            model_name='vendorsettlement',
            constraint=models.UniqueConstraint(fields=('vendor', 'period_start', 'period_end'), name='uniq_vendor_settle_period'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlementitem',
            index=models.Index(fields=['vendor', 'status'], name='idx_vsi_vendor_status'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlementitem',
            index=models.Index(fields=['status', 'eligible_at'], name='idx_vsi_status_eligible'),
        ),
        migrations.AddConstraint(
            model_name='vendorsettlementitem',
            constraint=models.UniqueConstraint(fields=('vendor', 'order'), name='uniq_vendor_order_settle'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlementpayment',
            index=models.Index(fields=['settlement', 'status'], name='idx_vsp_settle_status'),
        ),
    ]
