# Generated by Django 6.0.3 on 2026-10-01 12:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_vendorsettlement_vendorinvoice_settlement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReceivable',
            fields=[
                ('receivable_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_amount', models.DecimalField(db_column='goods_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('shipping_amount', models.DecimalField(db_column='shipping_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('adjustment_amount', models.DecimalField(db_column='adjustment_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_due', models.DecimalField(db_column='amount_due', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', '等待撥款資格'), ('eligible', '可撥款'), ('payout_pending', '撥款處理中'), ('partially_paid', '部分撥款'), ('paid', '已全額撥款'), ('refunded', '已退款'), ('cancelled', '已取消'), ('adjusted', '已調整')], db_column='status', default='pending', max_length=30)),
                ('eligible_at', models.DateTimeField(blank=True, db_column='eligible_at', null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_column='paid_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_receivables', to='api.order')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='api.vendor')),
            ],
            options={
                'db_table': 'Vendor_Receivable',
            },
        ),
        migrations.CreateModel(
            name='VendorReceivablePayout',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payout_method', models.CharField(choices=[('bank_transfer', '銀行轉帳'), ('manual', '人工撥款'), ('other', '其他')], db_column='payout_method', default='bank_transfer', max_length=30)),
                ('destination_bank_code', models.CharField(blank=True, db_column='destination_bank_code', max_length=20, null=True)),
                ('destination_account_last4', models.CharField(blank=True, db_column='destination_account_last4', max_length=4, null=True)),
                ('destination_account_name', models.CharField(blank=True, db_column='destination_account_name', max_length=100, null=True)),
                ('transaction_reference', models.CharField(blank=True, db_column='transaction_reference', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認撥款'), ('failed', '撥款失敗'), ('cancelled', '已取消')], db_column='status', default='pending', max_length=30)),
                ('payout_at', models.DateTimeField(blank=True, db_column='payout_at', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_column='confirmed_at', null=True)),
                ('note', models.TextField(blank=True, db_column='note', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='confirmed_by_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_vendor_receivable_payouts', to='api.admins')),
                ('receivable', models.ForeignKey(db_column='receivable_id', on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='api.vendorreceivable')),
            ],
            options={
                'db_table': 'Vendor_Receivable_Payout',
            },
        ),
        migrations.AddIndex(
            model_name='vendorreceivable',
            index=models.Index(fields=['vendor', 'status'], name='idx_vr_vendor_status'),
        ),
        migrations.AddIndex(
            model_name='vendorreceivable',
            index=models.Index(fields=['status', 'eligible_at'], name='idx_vr_status_eligible'),
        ),
        migrations.AddConstraint(
            model_name='vendorreceivable',
            constraint=models.UniqueConstraint(fields=('vendor', 'order'), name='uniq_vendor_order_receivable'),
        ),
        migrations.AddIndex(
            model_name='vendorreceivablepayout',
            index=models.Index(fields=['receivable', 'status'], name='idx_vrp_recv_status'),
        ),
    ]
