# Generated by Django 6.0.3 on 2026-10-01 18:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_vendorreceivable_vendorreceivablepayout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreceivable',
            name='status',
            field=models.CharField(choices=[('pending', '等待撥款資格'), ('eligible', '可納入月結'), ('included', '已納入月結'), ('payout_pending', '月結撥款處理中'), ('partially_paid', '部分撥款'), ('paid', '已全額撥款'), ('refunded', '已退款'), ('cancelled', '已取消'), ('adjusted', '已調整')], db_column='status', default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='VendorPayoutBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_column='period_start')),
                ('period_end', models.DateField(db_column='period_end')),
                ('goods_amount', models.DecimalField(db_column='goods_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('shipping_amount', models.DecimalField(db_column='shipping_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('adjustment_amount', models.DecimalField(db_column='adjustment_amount', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_due', models.DecimalField(db_column='amount_due', decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', '月結建立中'), ('ready', '待撥款'), ('paid', '已完成撥款'), ('failed', '撥款失敗'), ('cancelled', '已取消'), ('adjusted', '已調整')], db_column='status', default='draft', max_length=30)),
                ('payout_method', models.CharField(choices=[('bank_transfer', '銀行轉帳'), ('manual', '人工撥款'), ('other', '其他')], db_column='payout_method', default='bank_transfer', max_length=30)),
                ('destination_bank_code', models.CharField(blank=True, db_column='destination_bank_code', max_length=20, null=True)),
                ('destination_account_last4', models.CharField(blank=True, db_column='destination_account_last4', max_length=4, null=True)),
                ('destination_account_name', models.CharField(blank=True, db_column='destination_account_name', max_length=100, null=True)),
                ('transaction_reference', models.CharField(blank=True, db_column='transaction_reference', max_length=100, null=True)),
                ('scheduled_payout_date', models.DateField(blank=True, db_column='scheduled_payout_date', null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_column='paid_at', null=True)),
                ('note', models.TextField(blank=True, db_column='note', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='confirmed_by_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_vendor_payout_batches', to='api.admins')),
                ('vendor', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches', to='api.vendor')),
            ],
            options={
                'db_table': 'Vendor_Payout_Batch',
            },
        ),
        migrations.AddField(
            model_name='vendorreceivable',
            name='payout_batch',
            field=models.ForeignKey(blank=True, db_column='payout_batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='api.vendorpayoutbatch'),
        ),
        migrations.AddIndex(
            model_name='vendorreceivable',
            index=models.Index(fields=['payout_batch', 'status'], name='idx_vr_batch_status'),
        ),
        migrations.AddIndex(
            model_name='vendorpayoutbatch',
            index=models.Index(fields=['vendor', 'status'], name='idx_vpb_vendor_status'),
        ),
        migrations.AddIndex(
            model_name='vendorpayoutbatch',
            index=models.Index(fields=['period_start', 'period_end'], name='idx_vpb_period'),
        ),
        migrations.AddConstraint(
            model_name='vendorpayoutbatch',
            constraint=models.UniqueConstraint(fields=('vendor', 'period_start', 'period_end'), name='uniq_vendor_payout_period'),
        ),
    ]
