# Generated by Django 6.0.3 on 2026-10-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_vendorinvoice_remittance_account_last5_and_more'),
        ('api', '0052_vendorreceivable_vendorreceivablepayout_and_more'),
    ]

    operations = [
    ]
