# Generated by Django 6.0.3 on 2026-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_merge_20261003_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='remittance_account_last5',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='remittance_amount',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='remittance_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='remittance_date',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='remittance_reject_reason',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='remittance_reported_at',
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='status',
            field=models.CharField(choices=[('pending', '待開立'), ('issued', '開立成功'), ('failed', '開立失敗')], db_column='status', default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorsettlementpayment',
            name='status',
            field=models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('rejected', '已退回'), ('failed', '入帳失敗'), ('cancelled', '已取消')], db_column='status', default='pending', max_length=30),
        ),
    ]
