# Generated by Django 6.0.3 on 2026-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_vendorreceivable_status_vendorpayoutbatch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorpayoutbatch',
            name='uniq_vendor_payout_period',
        ),
        migrations.RemoveConstraint(
            model_name='vendorsettlement',
            name='uniq_vendor_settle_period',
        ),
        migrations.AddField(
            model_name='vendorpayoutbatch',
            name='batch_type',
            field=models.CharField(choices=[('regular', '正式月結'), ('supplemental', '補結算')], db_column='batch_type', default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorpayoutbatch',
            name='sequence',
            field=models.PositiveIntegerField(db_column='sequence', default=1),
        ),
        migrations.AddField(
            model_name='vendorsettlement',
            name='sequence',
            field=models.PositiveIntegerField(db_column='sequence', default=1),
        ),
        migrations.AddField(
            model_name='vendorsettlement',
            name='settlement_type',
            field=models.CharField(choices=[('regular', '正式月結'), ('supplemental', '補結算')], db_column='settlement_type', default='regular', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vendorpayoutbatch',
            constraint=models.UniqueConstraint(fields=('vendor', 'period_start', 'period_end', 'batch_type', 'sequence'), name='uniq_vendor_payout_period_type_seq'),
        ),
        migrations.AddConstraint(
            model_name='vendorsettlement',
            constraint=models.UniqueConstraint(fields=('vendor', 'period_start', 'period_end', 'settlement_type', 'sequence'), name='uniq_vendor_settle_period_type_seq'),
        ),
    ]
