# Generated by Django 6.0.3 on 2026-10-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_vendorinvoice_remittance_account_last5_and_more'),
        ('api', '0054_remove_vendorpayoutbatch_uniq_vendor_payout_period_and_more'),
    ]

    operations = [
    ]
