# Generated by Django 6.0.3 on 2026-10-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_inquirymessage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bundle',
            field=models.BooleanField(db_column='is_bundle', default=False),
        ),
        migrations.CreateModel(
            name='ProductBundleItem',
            fields=[
                ('bundle_item_id', models.AutoField(db_column='bundle_item_id', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity', default=1)),
                ('bundle', models.ForeignKey(db_column='bundle_product_id', on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='api.product')),
                ('component', models.ForeignKey(db_column='component_product_id', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='api.product')),
            ],
            options={
                'db_table': 'Product_Bundle_Item',
                'unique_together': {('bundle', 'component')},
            },
        ),
    ]
