# Generated by Django 6.0.3 on 2026-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_product_is_bundle_productbundleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='promo_copy',
            field=models.TextField(blank=True, db_column='promo_copy', default=''),
        ),
    ]
