# Generated by Django 6.0.3 on 2026-08-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0016_merge_20260809_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('payment_transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('merchant_trade_no', models.CharField(db_column='merchant_trade_no', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ecpay_trade_no', models.CharField(blank=True, db_column='ecpay_trade_no', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '付款成功'), ('failed', '付款失敗')], db_column='status', default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, db_column='raw_response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='api.order')),
            ],
            options={
                'db_table': 'PaymentTransaction',
            },
        ),
    ]
