# Generated by Django 6.0.3 on 2026-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', '待付款'), ('paid', '付款成功'), ('failed', '付款失敗'), ('refund_pending', '待退款')], db_column='status', default='pending', max_length=20),
        ),
    ]
